### ISSUE TITLE
Output appears mangled with RTL writing systems

### ISSUE THREAD

**Issue by cottongin** [sopel-irc/sopel-youtube#30]
I haven't had time to dig into this much so I am not 100% sure if this is unique to sopel-youtube or more an issue with Sopel itself, but try pasting any YouTube link that has Right to Left writing language anywhere in the title or channel name and the output appears completely mangled.

I did try this on a few different IRC clients as I originally thought this might just be an issue with my preferred client of choice, but I did observe the mangling on all clients I tested. Then again, perhaps this is a Windows thing.

Example:
```
20:33:15 <cottongin> https://www.youtube.com/watch?v=xHn-zrQ_rA8
20:33:16 <bot> [YouTube] لعبة الذاكرة (الحلقة ٧)  - الرياضة، لعبة البطاقات لكل العائلة – تعلم مع زكريا | 3m 30s | Channel: Learn with Zakaria - تعلم مع زكريا | 51,145 views | 900+ | 127- | Uploaded 1 week ago
```

Edit: I should note that my experience with RTL writing systems is basically nil, so I have no idea what the desired output would be here, if it is even easily fixable, or if this is "merely" an encoding issue.

**Comment by dgw** [comment]
Well, this is a meaty one.

I did some experimenting (and skimmed the intro sections of the [Unicode Bidirectional Algorithm](https://www.unicode.org/reports/tr9/)) to find some improvement:

![image](https://user-images.githubusercontent.com/164140/95037129-9a13a200-068f-11eb-8bfe-6824a8be9ddd.png)

Kaede runs the released version of sopel-youtube 0.3.2; SopelTest runs my local development version with some tweaks—the relevant one here being wrapping both the "title" and "channel name" values with Unicode directional isolate marks (FIRST STRONG ISOLATE and POP DIRECTIONAL ISOLATE, specifically).

Doing that at least prevents the fields from getting mixed up. In my normal portrait-display IRC window, part of the title (two of the three words making up the Arabic channel name, which is also repeated at the end of the title) gets sent to the second line. Moving the window to my landscape monitor and making it wide enough to fit the whole line fixes that:

![image](https://user-images.githubusercontent.com/164140/95037387-7866ea80-0690-11eb-95b8-66c6893aa053.png)

Not sure what else could be done about the wrapping there. While I did study Hebrew at one point, and have family who've studied Arabic, I'm nowhere near knowledgeable enough about bidi users' expectations to know the best move. Once the text's directionality is correctly marked to prevent text rendering engines from getting confused by the weak/neutral characters (i.e. numbers, whitespace, & punctuation) at or near the boundaries between semantic fields, I doubt anything we'd do here could improve on the client's (text renderer's) own bidi handling.

Sure, I'll probably take another look at this and the available standards/best-practices before making a formal PR, but right now I'm almost positive that directional isolate characters are the way to go. (Just too bad that we have to sacrifice another 8+ bytes per line to this, simply because it's hard to separate fields with strongly-directional characters that would look good as separators.)

**Comment by dgw** [comment]
Checking the directionality of every single character in the title and channel name, for the purpose of trying to save a few bytes, doesn't seem like a very efficient use of CPU cycles. Most links won't generate lines long enough to worry about the extra length anyway. (You'd need the video title, channel name, AND time format ALL to be long. And if it turns out to be a common enough issue, there's always `max_messages=2` or the new `trailing` parameter coming soon in sopel-irc/sopel#1958.)

All that is to say, have at testing #31 and see if you can break it. I couldn't. 😛

**Comment by cottongin** [comment]
Awesome, props for the quick fix. I'll repeat this on #31 as well but no issues so far with this patch... Hooray!  This may also be something to think about adding to other plugins which parse URLs and output information. URL and sopel-twitter being two I can think off of the top of my head.
